Add login page
DiviPeople/chen-web-client pull request #3
Opened 2023-06-09 14:41 UTC by GermanDrozdenko

2023-06-22 15:37 UTC, estromenko requested changes

2023-06-22 15:37 UTC, estromenko commented on src/routes/+layout.svelte
> +  <div class="">
Лишний пустой `class`

2023-06-22 15:37 UTC, estromenko commented on src/routes/login/+page.server.ts
> +import jwt_decode from 'jwt-decode'
Вместо snake_case должен быть camelCase: `jwtDecode`

2023-06-22 15:37 UTC, estromenko commented on src/routes/login/+page.server.ts
> +    let response = await fetch('http://localhost:8080/login', {
Можно применить `const` вместо `let`

2023-06-22 15:37 UTC, estromenko commented on src/routes/login/+page.server.ts
> +    let response = await fetch('http://localhost:8080/login', {
Такие url'ы лучше выносить в переменные окружения

2023-06-22 15:37 UTC, estromenko commented on src/routes/+layout.svelte
> +</div>
Полетела табуляция

2023-06-22 15:37 UTC, estromenko commented on src/routes/login/+page.server.ts
> +}
Нужна trailing comma

2023-06-22 15:37 UTC, estromenko commented on src/routes/login/+page.server.ts
> +      console.log(decoded)
Лишний `console.log()`

2023-06-22 15:37 UTC, estromenko commented on src/routes/login/+page.server.ts
> +      if (decoded.is_staff === true) {
Можно просто `if (decoded.is_staff) {}`

2023-06-22 15:37 UTC, estromenko commented on src/routes/login/+page.server.ts
> +    let result = await response.json()
Можно использовать `const`

2023-06-22 15:37 UTC, estromenko commented on src/routes/login/+page.server.ts
> +        'Content-Type': 'application/json'
Нужна trailing comma

2023-06-22 15:37 UTC, estromenko commented on src/routes/+layout.svelte
> +      <span class="self-center whitespace-nowrap text-xl font-semibold text-white"> ChenAPI </span>
Обязательны ли пробелы вокруг `ChenAPI`?

2023-06-22 15:37 UTC, estromenko commented on src/routes/+layout.svelte
> +      <img src="chen.png" class="mr-3 h-6 sm:h-11" alt="Flowbite Logo"/>
Нужен пробел перед `/>`

2023-06-27 14:47 UTC, Themanwhosmellslikesugar approved these changes

2023-06-27 14:47 UTC, merged